# This is a basic workflow that is manually triggered

name: Build

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      tag:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Tag for Release'
        # Default value if no value is explicitly provided
        default: '2.04'
        # Input has to be provided for the workflow to run
        required: true
jobs:
  build:

    runs-on: windows-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      with:
        vs-version: '16.5'
    - name: Install cURL
      run: choco install curl --acceptlicense --confirm
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Pyinstaller
      run: |
        python -m pip install --upgrade pip
    - name: Run Scripts
      run: build.cmd
      shell: cmd
    - name: Upload Files
      uses: actions/upload-artifact@v2
      with:
        name: Release
        path: "Kaizo Mario 3D World.exe"
    - name: Make a release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ github.event.inputs.tag }}"
        prerelease: false
        title: "Version ${{ github.event.inputs.tag }}"
        files: |
          Kaizo Mario 3D World.exe