# This is a basic workflow that is manually triggered

name: Build

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      tag:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Tag for Release'
        # Default value if no value is explicitly provided
        default: '2.02xc'
        # Input has to be provided for the workflow to run
        required: true
      body:
        description: 'Body for Release'
        default: |
          - brain update
          changes:
          - My brain hurts
          - Check stream vod for more context on why it hurts
          - it works
          - I changed thingie mayro said
          - no blind jump 1-2 fix
          - bug fix
          - 1-2 fix
          - 1-2
          - ow my brain
        required: true
jobs:
  build:

    runs-on: windows-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      with:
        vs-version: '16.5'
    - name: Install cURL
      run: choco install curl --acceptlicense --confirm
    - name: Run Scripts
      run: build.cmd
      shell: cmd
    - name: Upload Files
      uses: actions/upload-artifact@v2
      with:
        name: Release
        path: |
          Kaizo Mario 3D World Normal Mode.exe
          Kaizo Mario 3D World Practice Mode.exe
    - name: Make Release
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
          tag_name: ${{ github.event.inputs.tag }}
          release_name: Release ${{ github.event.inputs.tag }}
          body: |
            Changes in this Release
            ${{ github.event.inputs.tag }}
          draft: false
          prerelease: false
